// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT001', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('CT001', async function() {
    await driver.get("https://elias-espinheira.github.io/myStore/")
    await driver.manage().window().setRect({ width: 734, height: 700 })
    assert(await driver.findElement(By.css(".text-gd")).getText() == "Novas Coleções")
    assert(await driver.findElement(By.css(".color-azul:nth-child(2)")).getText() == "Looks para diversas ocasiões. Escolha o seu!")
    await driver.findElement(By.linkText("Destaques")).click()
    assert(await driver.findElement(By.css(".content .text-md")).getText() == "Destaques")
    assert(await driver.findElement(By.css(".content .text-titulo")).getText() == "Promoções")
    await driver.findElement(By.css("#song-1 > button")).click()
    assert(await driver.findElement(By.css("#song-1 > button")).getText() == "COMPRAR AGORA")
    await driver.findElement(By.id("back-to-top")).click()
    await driver.findElement(By.linkText("Contato")).click()
    assert(await driver.findElement(By.css("p:nth-child(1)")).getText() == "eliasespinheira.98@gmail.com")
    assert(await driver.findElement(By.css(".info p:nth-child(2)")).getText() == "+55 79 98893-1719")
    assert(await driver.findElement(By.css(".text > p:nth-child(3)")).getText() == "Aracaju(SE)")
    assert(await driver.findElement(By.css("h1:nth-child(3)")).getText() == "Fale Comigo")
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".fa-linkedin")).click()
    vars["win4168"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win4168"])
    assert(await driver.getTitle() == "Elias Espinheira | LinkedIn")
    await driver.close()
    await driver.switchTo().window(vars["root"])
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".fa-whatsapp")).click()
    vars["win7734"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win7734"])
    assert(await driver.getTitle() == "Compartilhe no WhatsApp")
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.id("back-to-top")).click()
    await driver.close()
  })
})
